// Mapa de nombre de país (según API-Football) a emoji de bandera
export const FLAGS: Record<string, string> = {
  // América del Norte y CONCACAF
  'United States': '🇺🇸',
  'Mexico': '🇲🇽',
  'Canada': '🇨🇦',
  'Panama': '🇵🇦',
  'Costa Rica': '🇨🇷',
  'Honduras': '🇭🇳',
  'Jamaica': '🇯🇲',
  'El Salvador': '🇸🇻',
  'Guatemala': '🇬🇹',
  'Cuba': '🇨🇺',
  'Trinidad and Tobago': '🇹🇹',
  'Haiti': '🇭🇹',
  'Curacao': '🇨🇼',
  // Sudamérica
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Colombia': '🇨🇴',
  'Ecuador': '🇪🇨',
  'Uruguay': '🇺🇾',
  'Venezuela': '🇻🇪',
  'Chile': '🇨🇱',
  'Peru': '🇵🇪',
  'Paraguay': '🇵🇾',
  'Bolivia': '🇧🇴',
  // Europa
  'France': '🇫🇷',
  'Germany': '🇩🇪',
  'Spain': '🇪🇸',
  'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Portugal': '🇵🇹',
  'Netherlands': '🇳🇱',
  'Belgium': '🇧🇪',
  'Italy': '🇮🇹',
  'Switzerland': '🇨🇭',
  'Croatia': '🇭🇷',
  'Serbia': '🇷🇸',
  'Austria': '🇦🇹',
  'Hungary': '🇭🇺',
  'Turkey': '🇹🇷',
  'Czech Republic': '🇨🇿',
  'Denmark': '🇩🇰',
  'Slovakia': '🇸🇰',
  'Poland': '🇵🇱',
  'Romania': '🇷🇴',
  'Georgia': '🇬🇪',
  'Greece': '🇬🇷',
  'Ukraine': '🇺🇦',
  'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Albania': '🇦🇱',
  'Slovenia': '🇸🇮',
  'Iceland': '🇮🇸',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Ireland': '🇮🇪',
  'Finland': '🇫🇮',
  'Bosnia': '🇧🇦',
  'North Macedonia': '🇲🇰',
  'Kosovo': '🇽🇰',
  'Russia': '🇷🇺',
  // Asia
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Iran': '🇮🇷',
  'Australia': '🇦🇺',
  'Saudi Arabia': '🇸🇦',
  'Iraq': '🇮🇶',
  'Jordan': '🇯🇴',
  'Qatar': '🇶🇦',
  'Uzbekistan': '🇺🇿',
  'China': '🇨🇳',
  'Indonesia': '🇮🇩',
  'India': '🇮🇳',
  'Palestine': '🇵🇸',
  'Lebanon': '🇱🇧',
  'Syria': '🇸🇾',
  'Bahrain': '🇧🇭',
  'Kuwait': '🇰🇼',
  'Oman': '🇴🇲',
  'Tajikistan': '🇹🇯',
  // África
  'Morocco': '🇲🇦',
  'Egypt': '🇪🇬',
  'South Africa': '🇿🇦',
  'DR Congo': '🇨🇩',
  'Senegal': '🇸🇳',
  'Nigeria': '🇳🇬',
  'Ghana': '🇬🇭',
  "Cote d'Ivoire": '🇨🇮',
  'Ivory Coast': '🇨🇮',
  'Cameroon': '🇨🇲',
  'Tunisia': '🇹🇳',
  'Algeria': '🇩🇿',
  'Mali': '🇲🇱',
  'Burkina Faso': '🇧🇫',
  'Cape Verde': '🇨🇻',
  'Angola': '🇦🇴',
  'Guinea': '🇬🇳',
  'Tanzania': '🇹🇿',
  'Kenya': '🇰🇪',
  'Mozambique': '🇲🇿',
  'Comoros': '🇰🇲',
  'Zambia': '🇿🇲',
  'Zimbabwe': '🇿🇼',
  // Oceanía
  'New Zealand': '🇳🇿',
  'Fiji': '🇫🇯',
  // Israel
  'Israel': '🇮🇱',
};

export function getFlag(countryName: string): string {
  return FLAGS[countryName] ?? '🏳️';
}
